name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Gerar animação da cobra
        uses: Platane/snk@v2
        with:
          github_user_name: nathanpw12 # Substitua pelo seu nome de usuário
          outputs: dist/snake.svg

      - name: Enviar arquivo gerado
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
